siteName: Trained Stoic
siteDescription: >-
  Exploring timeless wisdom for modern resilience. Learn practical Stoic
  philosophy to navigate life's challenges with greater peace, purpose, and
  inner strength.
siteUrl: https://trainedstoic.com
social:
  twitter: '@trainedstoic'
  linkedin: https://linkedin.com/company/trained-stoic
  github: https://github.com/trainedstoic
analytics:
  googleAnalyticsId: G-XXXXXXXXXX