/// <reference types="astro/client" />
/// <reference path="../.astro/types.d.ts" />
// This will be auto-generated by bknd when the app boots
/// <reference path="./bknd-types.d.ts" />

declare global {
  interface Window {
    Alpine: import("alpinejs").Alpine;
  }
}

export {};
